### ISSUE TITLE
[FEATURE] Add basic unittests

### ISSUE THREAD

**Issue by masadcv** [masadcv/numpymaxflow#15]
- Add basic unittests to cover both 2D and 3D cases
- Include unittests in CI (github workflows) to verify each PR before merging
- Include unittests to verify each release before publishing package to PyPi

**Comment by bz1977** [comment]
Hi
 I get an error when I install numpymaxflow.
 here is the error:
 (monailabel_env) c:\Users\bz197\MONAILabel>pip install numpymaxflow
Collecting numpymaxflow
  Using cached numpymaxflow-0.0.6.tar.gz (14 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Collecting setuptools
        Using cached setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
      Collecting numpy==1.22.0
        Using cached numpy-1.22.0.zip (11.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        Getting requirements to build wheel did not run successfully.
        exit code: 1

        [33 lines of output]
        Traceback (most recent call last):
          File "C:\ProgramData\anaconda3\envs\monailabel_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\ProgramData\anaconda3\envs\monailabel_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\ProgramData\anaconda3\envs\monailabel_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
            backend = _build_backend()
                      ^^^^^^^^^^^^^^^^
          File "C:\ProgramData\anaconda3\envs\monailabel_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
            obj = import_module(mod_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\ProgramData\anaconda3\envs\monailabel_env\Lib\importlib\__init__.py", line 90, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
          File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
          File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
          File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
          File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
          File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
          File "<frozen importlib._bootstrap_external>", line 994, in exec_module
          File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
          File "C:\Users\bz197\AppData\Local\Temp\pip-build-env-1cob792k\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
            import setuptools.version
          File "C:\Users\bz197\AppData\Local\Temp\pip-build-env-1cob792k\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
            import pkg_resources
          File "C:\Users\bz197\AppData\Local\Temp\pip-build-env-1cob792k\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
            register_finder(pkgutil.ImpImporter, find_on_path)
                            ^^^^^^^^^^^^^^^^^^^
        AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.



CAN YOU PLEASE HELP ME?

**Comment by masadcv** [comment]
Hi, 
Thanks for reaching out!
Can you create a new issue for this? Say a bug report and add the same detail. 
I also need additional detail about your setup. 
Can you provide output of `pip list` as well as OS and Python version. 

From initial look, it seems the error is not generated from numpymaxflow library, it is coming from another library in your setup.
